@startuml "Диаграмма вариантов использования"

actor Пользователь
actor Курьер
actor Администратор

rectangle "Система" {
    usecase "Регистрация и Авторизация" as Регистрация_и_Авторизация
    usecase "Просмотр Меню Ресторанов" as Просмотр_Меню
    usecase "Оформление Заказа" as Оформление_Заказа
    usecase "Отслеживание Заказа" as Отслеживание_Заказа
    usecase "Обратная Связь и Оценка" as Обратная_Связь
}

rectangle "Система управления заказами" {
    usecase "Управление Заказами" as Управление_Заказами
    usecase "Обновление Статусов Заказов" as Обновление_Статусов
}

Пользователь --> Регистрация_и_Авторизация
Пользователь --> Просмотр_Меню
Пользователь --> Оформление_Заказа
Пользователь --> Отслеживание_Заказа
Пользователь --> Обратная_Связь

Курьер --> Управление_Заказами
Курьер --> Обновление_Статусов

Администратор --> Управление_Заказами
Администратор --> Обновление_Статусов

Регистрация_и_Авторизация ..> Управление_Заказами : <<include>>
Оформление_Заказа ..> Управление_Заказами : <<include>>
Отслеживание_Заказа ..> Обновление_Статусов : <<include>>
Обратная_Связь ..> Управление_Заказами : <<include>>
@enduml
