@startuml ""
class МодульПользователя {
  +Регистрация()
  +Авторизация()
  +ПросмотрМеню()
  +ОформлениеЗаказа()
  +ОтслеживаниеЗаказа()
  +ОставитьОтзыв()
}

class МодульЗаказа {
  +СоздатьЗаказ()
  +ПодтвердитьЗаказ()
  +ОбновитьСтатусЗаказа()
  +ОтменитьЗаказ()
  +ПолучитьДеталиЗаказа()
}

class МодульРесторана {
  +ПолучитьМеню()
  +ПодтвердитьЗаказ()
  +ОбновитьСтатусПриготовления()
}

class МодульКурьера {
  +ПолучитьЗаказ()
  +ОбновитьСтатусДоставки()
  +ПодтвердитьДоставку()
}

class МодульОплаты {
  +ПроверитьОплату()
  +ОбработатьПлатеж()
  +ОтменитьПлатеж()
}

class МодульРасчетаВремениДоставки {
  +РассчитатьВремяДоставки()
  +ОбновитьОжидаемоеВремя()
}

МодульПользователя --> МодульЗаказа : Использует
МодульЗаказа --> МодульРесторана : Информирует
МодульЗаказа --> МодульКурьера : Информирует
МодульПользователя --> МодульОплаты : Использует
МодульКурьера --> МодульРасчетаВремениДоставки : Использует
МодульРесторана --> МодульРасчетаВремениДоставки : Информирует

@enduml
