@startuml "Диаграмма деятельности для описания процесса обработки заказа системой"
title Процесс обработки заказа системой

start
:Пользователь оформляет заказ;
:Система проверяет данные заказа;
if (Данные корректны?) then (да)
  :Система подтверждает заказ;
  :Система отправляет заказ в ресторан;
  :Ресторан принимает заказ;
  :Ресторан начинает готовить заказ;
  :Система обновляет статус заказа (готовится);
  :Ресторан завершает приготовление заказа;
  :Система уведомляет курьера о готовности заказа;
  :Курьер забирает заказ;
  :Система обновляет статус заказа (в пути);
  :Курьер доставляет заказ пользователю;
  :Пользователь подтверждает получение заказа;
  :Система завершает заказ;
  :Система запрашивает отзыв;
else (нет)
  :Система уведомляет пользователя о проблеме;
endif
stop
@enduml
