@startuml "Диаграмма последовательности для процесса заказа еды через приложение"
actor Пользователь
actor Курьер
participant "Мобильное Приложение" as App
participant "Система Управления Заказами" as OrderSystem
participant "Ресторан" as Restaurant

Пользователь -> App: Регистрация/Авторизация
App -> OrderSystem: Верификация данных пользователя
OrderSystem --> App: Подтверждение регистрации/авторизации

Пользователь -> App: Просмотр Меню Ресторанов
App -> OrderSystem: Запрос меню ресторанов
OrderSystem -> Restaurant: Запрос текущего меню
Restaurant --> OrderSystem: Текущее меню
OrderSystem --> App: Меню ресторанов
App --> Пользователь: Отображение меню

Пользователь -> App: Оформление Заказа
App -> OrderSystem: Создание нового заказа
OrderSystem -> Restaurant: Новый заказ
Restaurant --> OrderSystem: Подтверждение и время готовности заказа
OrderSystem --> App: Подтверждение заказа
App --> Пользователь: Подтверждение заказа и время ожидания

Restaurant -> Курьер: Уведомление о готовности заказа
Курьер -> Restaurant: Подтверждение получения заказа

Курьер -> OrderSystem: Статус доставки (забрал заказ)
OrderSystem -> App: Обновление статуса заказа
App --> Пользователь: Статус обновлен (заказ в пути)

Курьер -> Пользователь: Доставка заказа
Пользователь -> Курьер: Подтверждение получения заказа

Пользователь -> App: Оставить отзыв и оценку
App -> OrderSystem: Отправить отзыв и оценку
OrderSystem -> Restaurant: Отзыв и оценка
@enduml
