@startuml "Статусы Заказа"

[*] --> Создан
Создан --> Подтвержден : Подтверждение системой
Подтвержден --> Готовится : Принят рестораном
Готовится --> Готов : Заказ приготовлен
Готов --> В_пути : Забран курьером
В_пути --> Доставлен : Доставлен пользователю
Доставлен --> Получен : Подтвержден пользователем
Получен --> Оценен : Отзыв и оценка

Создан --> Отменен : Отмена пользователем
Подтвержден --> Отменен : Отмена пользователем
Готовится --> Отменен : Отмена пользователем
Готов --> Отменен : Отмена пользователем
@enduml
